### ISSUE TITLE
Sec-Metadata vs CORS

### ISSUE THREAD

**Issue by dhausknecht** [mikewest/sec-metadata#1]
Sec-Metadata sounds like a way to decide on the server if a request should be handled or blocked. Isn't CORS made for exactly that? What's the difference and why is it not enough?

**Edit**
Would it be enough to just extend CORS with the desired additional attributes instead of inventing a completely new mechanism?

**Comment by mikewest** [comment]
> `Sec-Metadata` sounds like a way to decide on the server if a request should be handled or blocked. Isn't CORS made for exactly that? What's the difference and why is it not enough?

CORS allows a server to grant a cross-origin requestor the ability to read an otherwise opaque response. It's a sharing mechanism, which allows the server to opt-out of the same-origin policy on a case-by-case basis.

That said, it's certainly true that servers can use the `Origin` header to make decisions about what to do with a request. I see this as doing the same thing.

> Would it be enough to just extend CORS with the desired additional attributes instead of inventing a completely new mechanism?

What would "extending CORS with the desired additional attributes" mean to you? I think it would mean sending the bits and pieces up to the server as a request header in order to allow the server to make a decision about whether or not to service the request, which is basically what this proposal does.

**Comment by dhausknecht** [comment]
> allow the server to make a decision about whether or not to service the request, which is basically what this proposal does.

indeed. Only that we do not need a new separate mechanism but simply allow to send more fine-grained information about where the request comes from and what we intent to do with it. Classic CORS can enforce the rest based on a decision made by the server. After all, cross-site requests seem to be the main target here and you would not need to design and implement a new enforcement mechanism.

Or am I missing something fundamental here? In any case I am not arguing against the proposal. I just wonder how to best design and implement it.

**Comment by mikewest** [comment]
> Only that we do not need a new separate mechanism but simply allow to send more fine-grained information about where the request comes from and what we intent to do with it.

I think this proposal does "send more fine-grained information about where the request comes from and what we intend to do with it". How would extending CORS look different from sending a request header that contains some metadata? It would be helpful if you could be more concrete.

**Comment by dhausknecht** [comment]
aaah, so I think I did get it wrong. I somehow understood it as something completely independent. But you sound like you just want to send a header. Period. No extra enforcement or anything. The relation to CORS was not mentioned anywhere. That's maybe how I got the wrong impression.

May I suggest then to send Sec-Metadata as part of a CORS preflight? Then a server could send the correct preflight response.

**Comment by mikewest** [comment]
> aaah, so I think I did get it wrong. I somehow understood it as something completely independent. But you sound like you just want to send a header. Period. No extra enforcement or anything.

That's correct. The proposal is to send additional metadata to the server. The server can then make a decision.

> The relation to CORS was not mentioned anywhere. That's maybe how I got the wrong impression.

What do you think the explainer should say about CORS?

> May I suggest then to send Sec-Metadata as part of a CORS preflight? Then a server could send the correct preflight response.

I don't see why we wouldn't included it in a CORS preflight, but I think we want to include it for `no-cors` requests as well, such as `<img>` and `<script>`, which are the basis of at least a subset of the timing attacks spelled out in the explainer.

**Comment by dhausknecht** [comment]
> but I think we want to include it for ```no-cors``` requests as well, such as ```<img>``` and ```<script>```

I find exactly that worth mentioning. CORS headers already give servers hints / meta data. But not for ```non-cors``` requests. This is where Sec-Metadata would jump in and provide the extra information.

> What do you think the explainer should say about CORS?

**What is the difference to CORS headers?**
Cross-Origin Resource Sharing (CORS) allows servers to make resource access decisions based on HTTP headers added to a request by the CORS mechanism. But not in all cases these headers are added, that is ```non-cors``` requests such as ```<img>``` and ```<script>```. In contrast, ```Sec-Metadata``` is added to all requests (including CORS requests and CORS preflight requests) and enables servers to make meaningful decisions in all cases.

Maybe something along these lines? It assumes that readers know how CORS works. I could not find where in the Fetch spec it says that ```<img>``` and ```<script>``` are ```non-cors``` requests. But I guess that's fine for a explainer not to have it.

**Comment by mikewest** [comment]
> What is the difference to CORS headers?

Ok. I'll add something along these lines. Thanks!

> I could not find where in the Fetch spec it says that `<img>` and `<script>` are `no-cors` requests.

Fetch is infrastructure that HTML uses to grab resources. So, for `<script>`, you'd want to look at https://html.spec.whatwg.org/multipage/scripting.html#script-processing-model, which calls out to https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-classic-script (passing in the `crossorigin` attribute as the CORS setting), which calls out to https://html.spec.whatwg.org/multipage/urls-and-fetching.html#create-a-potential-cors-request to create the request, setting its [mode](https://fetch.spec.whatwg.org/#concept-request-mode) to `no-cors`.

You'll find `<img>` processing instructions in HTML as well.

**Comment by dhausknecht** [comment]
> Ok. I'll add something along these lines. Thanks!

cool :-)

> Fetch is infrastructure that HTML uses to grab resources.

well, that explains why I couldn't find it. Thanks for the links
