### ISSUE TITLE
Sec-Fetch-Site vs intranet "sites"

### ISSUE THREAD

**Issue by anforowicz** [mikewest/sec-metadata#14]
Let's assume that there are 2 origins on the _intra_net:
- https://prod.corp.example.com
- https://images.corp.example.com

And let's assume that https://prod.corp.example.com/page.html embeds an image like so:
    <img src="https://images/image.png">

What should be the value of `Sec-Fetch-Site` header in this case?
- `cross-site` (because clearly the registrable domain of https://images is different from the registrable domain of https://prod.corp.example.com)?
- `same-site` (because https://image will ultimately resolve to https://image.corp.example.com)?

**Comment by mikewest** [comment]
I'd suggest `cross-site`, per the letter of the algorithms (`images` != `images.corp.example.com`, and therefore isn't same-site with `prod.corp.example.com`). I don't think we should bend over backwards to support naming schemes that humans could theoretically understand, but that computers wouldn't.
