### ISSUE TITLE
Trailing dot when determining same-site-edness for Sec-Fetch-Site

### ISSUE THREAD

**Issue by anforowicz** [mikewest/sec-metadata#15]
Should the spec explicitly spell out how to treat the trailing dot in hostnames?

For example, consider
- A page at https://some.example.com./page.html (note the trailing dot in the hostname)
- Embedding a same-origin (?) image: `<img src="https://some.example.com/page.html">`

In the example above, what should be the value of `Sec-Fetch-Site`?  `cross-site` or `same-origin`?

**Comment by mikewest** [comment]
Trailing dots are dumb. :(

They're separate origins (with distinct storage, etc) in at least Chrome and Firefox, and are distinct origins per the spec. I don't think we should carve out something special in this spec (though we might want to canonicalize in some other spec: see the issue in URL at https://url.spec.whatwg.org/#host-equivalence).

I think we'd actually end up with `same-site` with the current algorithms, as both `some.example.com` and `some.example.com.` would have `com` as their TLD, and `example.com` as their registerable domain, so they wouldn't compare as `same-origin`, but also wouldn't be `cross-site`.

**Comment by mikewest** [comment]
I'll add an explicit test to WPT and close this out, given the agreement between browsers and specs. That'll land in https://chromium-review.googlesource.com/c/chromium/src/+/1536180 once @sleevi explains to me whether Chromium is wrong or I'm wrong about how trailing dots intersect with registrable domains. :)

**Comment by mikewest** [comment]
I'm going to land a test marking these as `cross-site`, as that's the behavior Chrome displays, and I think it's the behavior Firefox would display if it implemented this feature (though I'm kinda guessing by skimming though code in Necko I don't understand!). https://github.com/publicsuffix/list/issues/792 should resolve this one way or the other, and I'll update the tests when it does.

**Comment by mikewest** [comment]
Tests landed, will continue the conversation around the PSL over there. 👉
