### ISSUE TITLE
Consider dropping default boolean headers.

### ISSUE THREAD

**Issue by mikewest** [mikewest/sec-metadata#19]
Requests will generally contain `Sec-Fetch-User: ?F`, which doesn't provide much value. Perhaps we can save some bandwidth by only sending boolean headers when they're interesting?

_(As discussed in https://github.com/mikewest/sec-metadata/issues/18#issuecomment-471869274)_

**Comment by mikewest** [comment]
@arturjanc, @yoavweiss: If we omit the header rather than sending an explicit `?F`, does `Vary: Sec-Fetch-User`, well, vary?

**Comment by yoavweiss** [comment]
My reading of [RFC 7234](https://tools.ietf.org/html/rfc7234#section-4.1) is that a request with a non-empty `Sec-Fetch-User` will vary from a request with an empty or non-existant `Sec-Fetch-User`.

A quick glance at the [relevant Chromium code](https://cs.chromium.org/chromium/src/net/http/http_vary_data.cc?gsn=request_digest_&g=0&l=53) also suggests that it will vary, as it seems to calculate the MD5 hash of the request value, even if that value is the empty string.

**Comment by arturjanc** [comment]
I did some quick testing and my observations agree with @yoavweiss's comment above: see the `Vary: width` tests at https://www.arturjanc.com/vary-check/index.html

Basically, when the server sends a `Vary` with a header name that is present in one request but not another, the browser doesn't return the cached result. I believe that's what we want.

**Comment by mikewest** [comment]
I'm dropping `Sec-Fetch-User` when it's `false`. If that turns out to be a terrible idea, we can add it back in later. :)
