### ISSUE TITLE
Is this spec been testing in Google Chrome already?

### ISSUE THREAD

**Issue by liuyanghejerry** [mikewest/sec-metadata#4]
I found this spec due to my Chrome sending header "Sec-Metadata" out within almost every requests. The behavior looks same as this spec. Just wondering if this spec been testing in Google Chrome already.

![image](https://user-images.githubusercontent.com/345442/46356625-b2621800-c695-11e8-90b3-aa87eb7dc6fd.png)

**Comment by mikewest** [comment]
If you've enabled "experimental web platform features" in your Chrome instance, then yes, you've got a mostly-complete implementation running locally. :)
