### ISSUE TITLE
Change "?F" and "?T" in `Sec-Fetch-User`

### ISSUE THREAD

**Issue by arturjanc** [mikewest/sec-metadata#8]
This syntax seems quite awkward in a response header; is there a precedent in other HTTP header values?

Instead, how about true / false, or 0 / 1? (for better or worse there are some headers with the latter convention)

**Comment by mikewest** [comment]
Odd or not, that's what @mnot et al settled on in https://tools.ietf.org/html/draft-ietf-httpbis-header-structure#section-3.11.

**Comment by arturjanc** [comment]
If this is part of SH and more or less a standard spelling, then it seems reasonable to stick to it in Sec-Metadata. It's still ugly, though! :)
